### ISSUE TITLE
CSS to render markdown's blockquote

### ISSUE THREAD

**Issue by thibault-v** [UrLab/incubator#441]
We can use markdown in most/all text editor of the website. The following (valid) markdown :
```markdown

> this is my quote

```
Will generate the following (valid) html :
```html
<blockquote>
<p>this is my quote</p>
</blockquote>
```
But, the incubator's CSS is not providing anything to render the "blockquote" tag :-/

I suggest that we add something like this in the website's css: 

```css
blockquote {
  padding-left: 10px;
  margin-left: 20px;
  border-left: solid;
  border-width: 2px;
  border-color: lightgrey;
  color: grey;
}
```
